name : CI Pipeline - Main
on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  GIT__BRANCH      : 'main'
  RELEASE_TYPE     : 'major'
  PACKAGE_NAME     : 'cbr_xyz'
  DOCKER__CONTEXT  : "."
  DOCKER__FILE     : './deploy/docker/cbr_xyz/Dockerfile'

jobs:

  run-tests:
    name: "Run tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "run-tests"
        uses: ./.github/actions/run-tests

  increment-tag:
    name: Increment Tag - Main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Increment Tag
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/git__increment-tag@dev
        with:
          release_type: ${{ env.RELEASE_TYPE }}
    needs:
      - run-tests

  publish-to-pypi:
    #if: False
    name: "Publish to: PYPI"
    permissions:
      id-token: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Git Update Current Branch
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/git__update_branch@dev

      - name: publish-to-pypi
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/pypi__publish@dev
    needs:
      - increment-tag

  publish-to-aws-ecr:
    name: "Publish to: AWS ECR"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Wait for PyPI publish"
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/pypi__wait-for-publish@dev

      - name: "Publish to: AWS ECR"
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/aws__publish__ecr@dev
        env:
          AWS_ACCOUNT_ID       : ${{ secrets.AWS_ACCOUNT_ID__654654216424        }}
          AWS_ACCESS_KEY_ID    : ${{ secrets.AWS_ACCESS_KEY_ID__654654216424     }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY__654654216424 }}
          AWS_DEFAULT_REGION   : ${{ secrets.AWS_DEFAULT_REGION__654654216424    }}
    needs:
      - publish-to-pypi

  deploy-lambda-function:
    name: Deploy Lambda Function
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests and Integration Tests
        uses: ./.github/actions/aws__deploy-lambda
        env:
          AWS_ACCOUNT_ID        : ${{ secrets.AWS_ACCOUNT_ID__654654216424        }}
          AWS_ACCESS_KEY_ID     : ${{ secrets.AWS_ACCESS_KEY_ID__654654216424     }}
          AWS_SECRET_ACCESS_KEY : ${{ secrets.AWS_SECRET_ACCESS_KEY__654654216424 }}
          AWS_DEFAULT_REGION    : ${{ secrets.AWS_DEFAULT_REGION__654654216424    }}
    needs:
      - publish-to-aws-ecr